- docs/changes.rst
- pipeline/__init__.py
- tests/test_messages.py
The current version of the common message structure allows for a
persistent message store to overwrite copies of the message with new
versions, using `'job_id'` as the index.. (This ability was enabled by
adding the `'events'` field.) The problem with this, however, is that
services in the Ingestion pipeline aren't always limited to one outgoing
message for each incoming message. In order to uniquely handle each
message sent through a service that sends multiple messages, there needs
to be a way to associated a new `job_id` with each outgoing message and
still preserve the link back to its incoming message.
A new function is being added to pipeline called `fanout` that will
handle all of the required behavior. To facilitate linking a message
back to its parent (and all of its ancestors), …
> Add a way to fan one message out from another

- pipeline/__init__.py
- pipeline/schema.py
Not only do we need to get better about pruning old versions from
docstrings when we begin working on the next release, we need to
remember to add them as we introduce changes.
> Clean up versions in docstrings

- docs/changes.rst
- pipeline/schema.py
We don't use the fields that track information about physical products
anywhere, nor do we track them for all of the providers. We've decided
to remove support for them from the database so there's no need to keep
them as part of the schema.
> Remove physical product-related fields from schema

- docs/changes.rst
- pipeline/__init__.py
- pipeline/schema.py
- tests/test_misc.py
We store UPCs and ISRCs as they are sent to us by the labels. This leads
to problems matching against Napster's catalog because they normalize
the values first. Going forward we want to start storing both the
normalized and raw versions.
> Add functionality to normalize identifiers

- pipeline/__init__.py
- tests/test_messages.py
By switching `fanout` from a regular function to a coroutine with an
appropriate signature, applications can register it as a result
postprocessor, allowing its callback's logic to remain unchanged.
> Make fanout available as a callback

- pipeline/schema.py
- tests/data/schema/invalid-track-action.json
- tests/data/schema/invalid-track-bundle-action.json
- tests/data/schema/invalid-track-bundle-amwkey.json
- tests/data/schema/invalid-track-bundle-provider.json
- tests/data/schema/invalid-track-bundle-title.json
- tests/data/schema/invalid-track-isrc.json
- tests/data/schema/invalid-track-usage-rules.json
- tests/data/schema/valid.json
- tests/test_schema.py
Usage rules have been rolled into the `'offers'` field (along with sales
territories). Not only should we stop requiring them, we shouldn't even
continue to support them.
Rather than using camel case for public fields and snake case for internal
use-only fields, all fields should use the same case. Since this is
essentially a JSON schema, JSON's convention of camel case should be used.
> Clean up product schema

- docs/changes.rst
- pipeline/schema.py
- tests/data/schema/valid.json
Made the change to the schema and added an offerless track to the valid delivery to cover that behavior.
> Accept empty offers on product schema

- docs/changes.rst
- pipeline/schema.py
Added `Optional` track level `grid` validation so we can begin to persist that field again.
> Add Track GRid To Schema

- docs/changes.rst
- pipeline/schema.py
- setup.py
- tests/data/schema/invalid-offer-commercial-model-type.json
- tests/data/schema/invalid-offer-licensee.json
- tests/data/schema/invalid-offer-territory-code.json
- tests/data/schema/invalid-offer-use-type.json
- tests/data/schema/invalid-offer-valid-from.json
- tests/data/schema/invalid-offer-valid-to.json
- tests/data/schema/valid-offer.json
- tests/test_schema.py
- swapped out the `voluptuous` `Datetime()` validator for a custom validator (`OffsetAwareDatetime`), that uses `python-dateutil` underneath the hood, so we can parse *any* UTC date with an offset value other than `Z`
- updated `changes.rst`
- unit tests to test valid and invalid (every type) `offers`
***NOTE***: The existing validation allows null values for `validFrom` and `validThrough`, so I kept it the same. Someone who cares should give the definitive answer to this.
> Change Offers Date Validation To dateutil.parser.parse

- pipeline/schema.py
Might as well stop using `voluptuous.Datetime` everywhere.
> Stop Using Old Voluptuous Datetime

- pipeline/schema.py
- tests/data/schema/valid-nulled-schema.json
- tests/test_schema.py
Using voluptuous' `Any()` to added `None` to product documents passed in by `detox`. 
These are the two services that would be affected by this and need to be updated:
https://github.com/iheartradio/objectify/search?q=pipeline.schema&unscoped_q=pipeline.schema
https://github.com/iheartradio/persist/search?q=pipeline.schema&unscoped_q=pipeline.schema
I pull the latest branches for these two services, pointed their requirements to this branch, pip  installed, and tox tested. They both passed without issues.
> Add None as acceptable for Optional fields.

- pipeline/schema.py
This method needs to account for `None`, which results in a `NoneType` TypeError. This is affecting `objectify` further downstream. 
Checking for the non value first before it checks the function. It should make this faster.
`Any(None, <type>)` -> `Any(None,<type>)`
> Adding NoneType Error to OffsetAwareDatetime.

- docs/changes.rst
- pipeline/__init__.py
- tests/test_messages.py
For each bread crumb event, we no longer need to capture `message['message']`. It's causing our message sizes to get out of control, and if someone really needs to get that message, there is a `job_id` that can be used as a reference to the original message itself.
Here are the following stats for message size changes across our 3 main pipelines:
```
MUSIC
21,862 messages = 2.5GB (Old Message Structure) 
21.862 messages = 158MB (New Message Structure)
93.68% Decrease In Message Size
NAPSTER
23,405 messages = 16GB (Old Message Structure)
23,405 messages = 146MB (New Message Structure)
99.1% Decrease In Message Size
MRI
21,792 messages = 1GB (Old Message Structure)
21,792 messages = 69MB (New Message Structure)
93.1% Decrease In Message Size
```
> Reduce Breadcrumb Size

- docs/changes.rst
- pipeline/__init__.py
- tests/test_misc.py
ISRC needs to be uppercased to ensure a proper match throughout the pipeline.
> Added uppercased ISRC as part of normalization.

- docs/changes.rst
- setup.py
Incrementing the minor version requires resetting the patch version, so `2.1.1` becomes `2.2.0` rather than `2.2.1`.
> Fix semantic version

- .travis.yml
This PR updates the Slack secret for Travis CI and removes unneeded HipChat notifications.
> Update secret for Travis CI

- docs/changes.rst
- pipeline/schema.py
- setup.py
- tests/data/schema/valid-nulled-schema.json
Some deliveries have tracks that don't have `<Genre>`, but we shouldn't block these products from making their way through the pipeline, so here, we're making it `Optional`.
> Genre Is Optional

- docs/changes.rst
- pipeline/__init__.py
- setup.py
- tests/conftest.py
Currently send_message only accepts routing_key. This change allows the use of the specified exchange_name as the outbound exchange to route to. 
This change allows for specifying the exchange we would like to send a message to, similar to the routing_key change prior.
This also bumps up the version from 2.3.0 to 2.4.0, but this change should keep backward compatibility.
> Add support for exchange_name on send.

- docs/changes.rst
- pipeline/schema.py
- setup.py
- tests/data/schema/valid-nulled-schema.json
- tests/data/schema/valid.json
This PR updates the artist key in the product document to optionally include an `artists` key which includes a list of individually listed artists in the DDEX delivery.
This also bumps up the version from 2.4.0 to 2.5.0, but this change should keep backward compatibility as DDEX deliveries might not list individual artists. Also this should work for non-ddex, hence `artists` being optional.
> Updating artist schema to include multiple artists

- .travis.yml
- README.rst
- scripts/deploy.sh
- setup.py
- tox.ini
This PR:
- Removes sphinx docs build step
- Updates travis and build related files to enable automatically building and pushing this library to CodeArtifact
Things I specifically need sign off on:
- I've renamed the library from `pipeline` to `pipeline-ihr`. This is my personal recommendation to avoid the headache of naming conflicts with PyPi. There are additional steps we should take to mitigate this, such as setting the pip `--index-url` flag while installing private repos. But if we depart from using that process in the future, and to improve ease of working with this library in general, I think adding the ihr suffix gives us some redundancy in avoiding non-malicious naming conflicts.
- Getting rid of sphinx
More info on how unreliably pip decides which index to get packages from: …
> add codeartifact setup
